$id: dev.wombat.component.nats.core.output.config
title: OutputConfig
type: object
properties:
  subject:
    type: string
    description: >
      The subject to publish to.
      The subject may not contain wildcards, but may contain variables that are extracted from the message being processed.
  metadata:
    type: object
    description: >
      Optional metadata filters
    properties:
      patterns:
        type: array
        items:
          type: string
        description: >
          A list of regular expressions to match metadata fields.
          If set, only the metadata fields that match the patterns will be included in the output.
      invert:
        type: boolean
        description: >
          If set to true, the metadata fields that match the patterns will be excluded from the output.
          If set to false, the metadata fields that match the patterns will be included in the output.
        default: false
    required: 
      - patterns
      - invert 
required:
  - subject