version: "3"

silent: true

tasks:
  models:deps:
    cmds:
      - go install github.com/atombender/go-jsonschema@84c8d2b98bf0373873df8a353b122530a7110c70

  models:generate:
    deps: [ "models:deps" ]
    cmds:
      - go-jsonschema --struct-name-from-title
        --package nats
        --schema-output=dev.wombat.component.nats.core.system.config=./system_config.go
        --schema-output=dev.wombat.component.nats.core.input.config=./input_config.go
        --schema-output=dev.wombat.component.nats.core.output.config=./output_config.go
        *.schema.yaml

  test:
    desc: Run NATS component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build NATS component
    cmds:
      - go build ./...

  lint:
    desc: Lint NATS component
    cmds:
      - go vet ./...
      - gofmt -l .

  format:
    desc: Format NATS component code
    cmds:
      - go fmt ./...
      - goimports -w . || echo "goimports not available"