version: "3"

silent: true

vars:
  GO_MODULE: github.com/wombatwisdom/components

includes:
  components:
    taskfile: ./components/Taskfile.yml
    dir: ./components
  framework:
    taskfile: ./framework/Taskfile.yml 
    dir: ./framework

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  # Development Environment
  setup:
    desc: Setup development environment
    cmds:
      - go version
      - go work sync
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install github.com/atombender/go-jsonschema@84c8d2b98bf0373873df8a353b122530a7110c70

  test:
    desc: Run all tests in workspace
    cmds:
      - task: framework:test
      - task: components:all:test

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - task: framework:test:coverage
      - task: components:all:test:coverage

  test:race:
    desc: Run tests with race detector
    cmds:
      - task: framework:test:race
      - task: components:all:test:race

  validate:
    desc: Validate all modules
    cmds:
      - task: framework:validate
      - task: components:all:validate
        
  build:
    desc: build all workspace modules
    cmds:
      - task: framework:build
      - task: components:all:build

  deps:sync:
    desc: Sync workspace dependencies
    cmds:
      - go work sync