version: "3"

tasks:
  models:deps:
    cmds:
      - go install github.com/atombender/go-jsonschema@84c8d2b98bf0373873df8a353b122530a7110c70

  models:generate:
    deps: [ "models:deps" ]
    cmds:
      - go-jsonschema --struct-name-from-title
        --package mq
        --schema-output=dev.wombat.component.mq.system.config=./system_config.go
        --schema-output=dev.wombat.component.mq.input.config=./input_config.go
        --schema-output=dev.wombat.component.mq.output.config=./output_config.go
        *.schema.yaml

  test:
    desc: Run MQ component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build MQ component
    cmds:
      - go build ./...

  lint:
    desc: Lint MQ component
    cmds:
      - go vet ./...
      - gofmt -l .

  format:
    desc: Format MQ component code
    cmds:
      - go fmt ./...
      - goimports -w . || echo "goimports not available"