$id: dev.wombat.component.mq.output.config
title: OutputConfig
type: object
properties:
  queue_name:
    type: string
    description: >
      The IBM MQ queue name to write messages to.
    example: TEST_OUT
  ccsid:
    type: string
    description: >
      The Coded Character Set Identifier for the message.
      Determines the character encoding of the message data.
    default: "1208"
    example: "1208"
  encoding:
    type: string
    description: >
      The encoding of the message data.
      Specifies how numeric data is represented.
    default: "546"
    example: "546"
  format:
    type: string
    description: >
      The format of the message data.
      Indicates the structure and format of the message content.
    default: MQSTR
    example: MQSTR
  num_threads:
    type: integer
    description: >
      Number of parallel queue manager connections to use.
      Higher values can improve throughput for high-volume outputs.
    default: 1
    minimum: 1
  metadata:
    type: object
    description: >
      Optional metadata filters for message headers.
    properties:
      patterns:
        type: array
        items:
          type: string
        description: >
          A list of regular expressions to match metadata fields.
          If set, only matching metadata fields will be included as MQ message properties.
      invert:
        type: boolean
        description: >
          If true, exclude metadata fields that match the patterns.
          If false, include only metadata fields that match the patterns.
        default: false
    required:
      - patterns
      - invert
required:
  - queue_name