$id: dev.wombat.component.mq.system.config
title: SystemConfig
type: object
properties:
  queue_manager_name:
    type: string
    description: >
      The IBM MQ Queue Manager name.
      This identifies the queue manager to connect to.
    example: QM1
  channel_name:
    type: string
    description: >
      The IBM MQ channel name for client connections.
    default: SYSTEM.DEF.SVRCONN
    example: USER.CHANNEL
  connection_name:
    type: string
    description: >
      The IBM MQ connection name in the format hostname(port).
    default: localhost(1414)
    example: 192.168.56.1(1444)
  user_id:
    type: string
    description: >
      Optional: The IBM MQ user ID for authentication.
      This is a sensitive field and you may want to use environment variables.
    example: pcsuser
  password:
    type: string
    description: >
      Optional: The IBM MQ user password for authentication.
      This is a sensitive field and you may want to use environment variables.
  application_name:
    type: string
    description: >
      Optional: Application name for MQ connection identification.
    default: WombatWisdom MQ Component
  tls:
    type: object
    description: >
      Optional TLS configuration for encrypted connections.
    properties:
      enabled:
        type: boolean
        description: Enable TLS encryption for the MQ connection.
        default: false
      cipher_spec:
        type: string
        description: >
          The cipher specification for TLS encryption.
          Examples: ANY_TLS12_OR_HIGHER, ANY_TLS12, TLS_RSA_WITH_AES_128_CBC_SHA256
        default: ANY_TLS12_OR_HIGHER
      key_repository:
        type: string
        description: >
          Path to the key repository containing certificates.
          This is a sensitive field and you may want to use environment variables.
      key_repository_password:
        type: string
        description: >
          Password for the key repository.
          This is a sensitive field and you may want to use environment variables.
      certificate_label:
        type: string
        description: >
          Optional: Label of the certificate to use from the key repository.
          If empty, the default label 'ibmwebspheremq{username}' will be used.
    required:
      - enabled
required:
  - queue_manager_name