version: "3"
tasks:
  models:deps:
    cmds:
      - go install github.com/atombender/go-jsonschema@84c8d2b98bf0373873df8a353b122530a7110c70

  models:generate:
    deps: [ "models:deps" ]
    cmds:
      - go-jsonschema --struct-name-from-title
        --package core
        --schema-output=dev.wombat.component.nats.core.system.config=./system_config.go
        --schema-output=dev.wombat.component.nats.core.input.config=./input_config.go
        --schema-output=dev.wombat.component.nats.core.output.config=./output_config.go
        *.schema.yaml