version: "3"

tasks:
  test:
    desc: Run MQTT component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build MQTT component (currently has compatibility issues)
    cmds:
      - echo "⚠️  MQTT component needs interface updates to work with enhanced spec"
      - echo "   - Update sink.go to use new spec.Message interface"
      - echo "   - Update source.go to use new spec.Collector interface"
      - echo "   - Fix Environment interface compatibility"
      - echo "   Run 'task mqtt:migrate' to apply fixes"

  migrate:
    desc: Migrate MQTT component to enhanced spec interfaces
    cmds:
      - echo "🔄 Migrating MQTT component interfaces..."
      - echo "   This would update:"
      - echo "   - message.Data() → message.Raw()"
      - echo "   - DynamicField.AsString() → DynamicField.String()"
      - echo "   - Environment interface compatibility"
      - echo "   - Collector interface methods"
      - echo "⚠️  Manual migration required - see spec/ package for new interfaces"

  status:
    desc: Show MQTT component status
    cmds:
      - echo "📊 MQTT Component Status:"
      - echo "   ✅ Message interface partially updated"
      - echo "   ❌ Sink component needs interface fixes"
      - echo "   ❌ Source component needs interface fixes"
      - echo "   ❌ Environment interface needs updates"
      - echo ""
      - echo "💡 Next steps:"
      - echo "   1. Update sink.go DynamicField usage"
      - echo "   2. Update source.go Collector interface"
      - echo "   3. Fix Environment/Logger interface conflicts"