version: "3"

tasks:
  test:
    desc: Run S3 component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build S3 component (currently has compatibility issues)
    cmds:
      - echo "⚠️  S3 component needs interface updates to work with enhanced spec"
      - echo "   - Update source.go to use new spec.Message interface"  
      - echo "   - Remove .Ack()/.Nack() calls (now in legacy methods)"
      - echo "   - Fix Environment interface compatibility"
      - echo "   Run 'task s3:migrate' to apply fixes"

  migrate:
    desc: Migrate S3 component to enhanced spec interfaces
    cmds:
      - echo "🔄 Migrating S3 component interfaces..."
      - echo "   This would update:"
      - echo "   - Remove msg.Ack()/msg.Nack() calls"
      - echo "   - Update Environment interface usage"
      - echo "   - Fix Collector interface methods"
      - echo "⚠️  Manual migration required - see spec/ package for new interfaces"

  status:
    desc: Show S3 component status
    cmds:
      - echo "📊 S3 Component Status:"
      - echo "   ✅ Message interface updated (ObjectResponseMessage)"
      - echo "   ❌ Source component needs interface fixes"
      - echo "   ❌ Environment interface needs updates"
      - echo ""
      - echo "💡 Next steps:"
      - echo "   1. Remove legacy .Ack()/.Nack() method calls"
      - echo "   2. Update source.go Collector interface usage"
      - echo "   3. Fix Environment/Logger interface conflicts"