version: "3"

silent: true

tasks:
  test:
    desc: Run AWS S3 component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build AWS S3 component
    cmds:
      - go build ./...

  lint:
    desc: Lint AWS S3 component
    cmds:
      - go vet ./...
      - gofmt -l .

  format:
    desc: Format AWS S3 component code
    cmds:
      - go fmt ./...
      - goimports -w . || echo "goimports not available"

  deps:tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy