version: "3"

silent: true

vars:
  SHOW_PROGRESS: "true"

includes:
  common:
    taskfile: ../_common/Taskfile.yml

tasks:
  validate:
    desc: Validate the component
    cmds:
      - task: common:validate
        vars:
          SHOW_PROGRESS: "{{.SHOW_PROGRESS}}"
  
  test:
    desc: Run component tests
    cmds:
      - task: common:test

  test:unit:
    desc: Run unit tests only
    cmds:
      - task: common:test:unit

  test:integration:
    desc: Run integration tests only
    cmds:
      - task: common:test:integration

  test:coverage:
    desc: Run component tests with coverage
    cmds:
      - task: common:test:coverage

  test:race:
    desc: Run component tests with race detector
    cmds:
      - task: common:test:race
      
  build:
    desc: Build the component
    cmds:
      - task: common:build

  vet:
    desc: Run go vet on component
    cmds:
      - task: common:vet

  format:
    desc: Format component Go code
    cmds:
      - task: common:format
