version: "3"

tasks:
  test:
    desc: Run MQTT component tests
    cmds:
      - go test ./... -v

  build:
    desc: Build MQTT component
    cmds:
      - go build ./...

  lint:
    desc: Lint MQTT component
    cmds:
      - go vet ./...
      - gofmt -l .

  format:
    desc: Format MQTT component code
    cmds:
      - go fmt ./...
      - goimports -w . || echo "goimports not available"

  deps:tidy:
    desc: Tidy dependencies
    cmds:
      - go mod tidy