version: "3"

silent: true

vars:
  SHOW_PROGRESS: "true"

includes:
  common:
    taskfile: ../_common/Taskfile.yml
    vars:
      SHOW_PROGRESS: "{{.SHOW_PROGRESS}}"

tasks:
  validate:
    desc: Validate the component
    cmds:
      - task: common:validate
  
  test:
    desc: Run component tests
    cmds:
      - task: common:test

  test:coverage:
    desc: Run component tests with coverage
    cmds:
      - task: common:test:coverage

  test:race:
    desc: Run component tests with race detector
    cmds:
      - task: common:test:race
        
  build:
    desc: Build the component
    cmds:
      - task: common:build